### ISSUE TITLE
Inconsistencies with SSE and Layer extensions

### ISSUE THREAD

**Issue by redoPop** [murillo128/webrtc-http-egress-protocol#13]
Currently the spec, its examples, and the [Medooze reference lib (whep.js)](https://github.com/medooze/whip-whep-js/blob/main/whep.js) all use different values of `rel` for the SSE and Layer extensions:

* SSE rel variants:
    * `urn:ietf:params:whep:ext:sse` [(source)](https://github.com/murillo128/webrtc-http-egress-protocol/blob/8582f9d63903095f3658757f1adbe7c82a15e9b5/draft-murillo-whep.md?plain=1#L355)
    * `urn:ietf:params:whep:ext:core:server-sent-events` [(source)](https://github.com/murillo128/webrtc-http-egress-protocol/blob/8582f9d63903095f3658757f1adbe7c82a15e9b5/draft-murillo-whep.md?plain=1#L362)
    * `urn:ietf:params:whip:core:server-sent-events` [(source)](https://github.com/medooze/whip-whep-js/blob/main/whep.js#L147)
* Layer rel variants:
    * `urn:ietf:params:whep:ext:layer` [(source)](https://github.com/murillo128/webrtc-http-egress-protocol/blob/8582f9d63903095f3658757f1adbe7c82a15e9b5/draft-murillo-whep.md?plain=1#L496)
    * `urn:ietf:params:whep:ext:core:layer` [(source)](https://github.com/murillo128/webrtc-http-egress-protocol/blob/8582f9d63903095f3658757f1adbe7c82a15e9b5/draft-murillo-whep.md?plain=1#L503)
    * `urn:ietf:params:whip:core:layer` [(source)](https://github.com/medooze/whip-whep-js/blob/main/whep.js#L150)

I imagine `urn:ietf:params:whep:ext:sse` and `urn:ietf:params:whep:ext:layer` are the intended values, but the ambiguity seems to be causing some fragmentation:

* Dolby is currently using the values that appear in the reference implementation
* Janus' SSE PR (meetecho/simple-whep-server#3) uses the value that appears in the spec's example

We should fix the discrepancy before there's too much fragmentation.

**Comment by murillo128** [comment]
Thank you for pointing it out, could you double check that everything is consistent?

**Comment by redoPop** [comment]
Looking good, thank you!
